### ISSUE TITLE
More OverView Stats 2.1

### ISSUE THREAD

**Issue by zee0810** [Kazuwuqt/Anki_More_Overview_Stats#4]
Hi, 

I'm currently using anki 2.1.21 and downloaded the MoreOverView Stats 2.1. 
However, somehow, it's not showing up! Tried restarting anki but still nothing. 

EDIT: I think it's working now :)

**Comment by patrick-mahnkopf** [comment]
Hi,

the add-on changes the deck overview screen, but none of your screenshots include that screen.
Can you please click on one of your decks and check if it's showing up there?

It also looks like you might not actually be using my add-on, but an add-on called "More Overview Stats" by a different author, it should otherwise list it as "More Overview Stats 21" in your add-on list (notice the missing 21 in the name).
So please make sure you're using the add-on from [this link](https://ankiweb.net/shared/info/738807903) or just use this number to install the add-on in Anki: 738807903

Please let me know if your issue has been solved or if you require further assistance.

**Comment by patrick-mahnkopf** [comment]
I'll close the issue for now, but please feel free to re-open it if you require further assistance.
